# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  SERVER_BINARY: cmd/gophermart/gophermart.exe
  ACCRUAL_BINARY: cmd/accrual/accrual_windows_amd64

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -f {{.SERVER_BINARY}}

  build:
    desc: Build gophermart app
    cmds:
      - go build -o {{.SERVER_BINARY}} ./cmd/gophermart/
    sources:
      - "**/*.go"
    generates:
      - "{{.SERVER_BINARY}}"

  test:
    desc: Run tests
    cmds:
      - go test -v ./...
