ALTER TABLE users DROP CONSTRAINT IF EXISTS users_login_unique;

ALTER TABLE users DROP CONSTRAINT IF EXISTS users_pkey;

ALTER TABLE users DROP COLUMN IF EXISTS id;

DROP SEQUENCE IF EXISTS users_id_seq;

ALTER TABLE users ADD PRIMARY KEY (login);
